export const jogadores = [
  { nome: 'Lionel Messi', habilidade: 94, valorMercado: 120 },
  { nome: 'Cristiano Ronaldo', habilidade: 93, valorMercado: 100 },
  { nome: 'Neymar', habilidade: 92, valorMercado: 180 },
  // { nome: 'Kevin De Bruyne', habilidade: 91, valorMercado: 70 },
  // { nome: 'Robert Lewandowski', habilidade: 91, valorMercado: 60 },
  // { nome: 'Kylian Mbappé', habilidade: 90, valorMercado: 160 },
  // { nome: 'Virgil van Dijk', habilidade: 90, valorMercado: 70 },
  // { nome: 'Sadio Mane', habilidade: 90, valorMercado: 60 },
  // { nome: 'Bernardo Silva', habilidade: 89, valorMercado: 60 },
  // { nome: 'Raheem Sterling', habilidade: 89, valorMercado: 80 },
  // { nome: 'Jan Oblak', habilidade: 89, valorMercado: 50 },
  // { nome: 'Sergio Ramos', habilidade: 89, valorMercado: 40 },
  // { nome: 'Sergio Aguero', habilidade: 89, valorMercado: 80 },
  // { nome: 'Alisson Becker', habilidade: 88, valorMercado: 60 },
  // { nome: 'Giorgio Chiellini', habilidade: 88, valorMercado: 20 },
  // { nome: 'Marcelo', habilidade: 88, valorMercado: 30 },
  // { nome: 'Luka Modric', habilidade: 88, valorMercado: 40 },
  // { nome: 'Sergio Busquets', habilidade: 88, valorMercado: 40 },
  // { nome: 'Jordi Alba', habilidade: 87, valorMercado: 40 },
  // { nome: 'Ivan Rakitic', habilidade: 87, valorMercado: 30 },
  // { nome: 'Luis Alberto', habilidade: 87, valorMercado: 20 },
  // { nome: 'Houssem Aouar', habilidade: 87, valorMercado: 40 },
  // { nome: 'Memphis Depay', habilidade: 87, valorMercado: 50 },
  // { nome: 'Thomas Muller', habilidade: 87, valorMercado: 50 },
  // { nome: 'Jerome Boateng', habilidade: 87, valorMercado: 20 },
  // { nome: 'Kingsley Coman', habilidade: 86, valorMercado: 40 },
  // { nome: 'Joshua Kimmich', habilidade: 86, valorMercado: 50 },
  // { nome: 'Kalidou Koulibaly', habilidade: 86, valorMercado: 60 },
  // { nome: 'Dries Mertens', habilidade: 86, valorMercado: 40 },
  // { nome: 'Lorenzo Insigne', habilidade: 85, valorMercado: 40 },
  // { nome: 'Arkadiusz Milik', habilidade: 85, valorMercado: 30 },
  // { nome: 'Piotr Zielinski', habilidade: 85, valorMercado: 30 },
  // { nome: 'Marek Hamsik', habilidade: 85, valorMercado: 20 },
  // { nome: 'Fabian Ruiz', habilidade: 85, valorMercado: 40 },
  // { nome: 'Allan', habilidade: 85, valorMercado: 30 },
  // { nome: 'Kostas Manolas', habilidade: 85, valorMercado: 40 },
  // { nome: 'Nikola Maksimovic', habilidade: 85, valorMercado: 20 },
  // { nome: 'Faouzi Ghoulam', habilidade: 85, valorMercado: 20 },
  // { nome: 'Jose Callejon', habilidade: 85, valorMercado: 20 },
  // { nome: 'Allan Saint-Maximin', habilidade: 84, valorMercado: 20 },
  // { nome: 'Adrien Rabiot', habilidade: 84, valorMercado: 30 },
  // { nome: 'Alex Sandro', habilidade: 84, valorMercado: 30 },
  // { nome: 'Danilo', habilidade: 84, valorMercado: 20 },
  // { nome: 'Rodrigo Bentancur', habilidade: 84, valorMercado: 20 },
  // { nome: 'Blaise Matuidi', habilidade: 84, valorMercado: 20 },
  // { nome: 'Paulo Dybala', habilidade: 84, valorMercado: 40 },
  // { nome: 'Juan Cuadrado', habilidade: 84, valorMercado: 20 },
  // { nome: 'Cristiano Piccini', habilidade: 83, valorMercado: 10 },
  // { nome: 'Miralem Pjanic', habilidade: 83, valorMercado: 20 },
  // { nome: 'Douglas Costa', habilidade: 83, valorMercado: 20 },
  // { nome: 'Federico Bernardeschi', habilidade: 83, valorMercado: 20 }
]